# -*- coding: utf-8 -*-
"""
Generate *_image_urls.py files from Yandex Maps search.

For each guide, searches Yandex Maps by place name and generates image URLs.
Outputs Python dict format compatible with existing *_image_urls.py structure.
"""

from __future__ import annotations

import sys
from pathlib import Path

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from scripts.slug_item_map import GUIDES, _load_places, _basename, basename_to_slug
from scripts.yandex_maps_images import get_place_images


def generate_urls_for_guide(guide: str, dry_run: bool = False) -> dict[str, str]:
    """
    Generate image URLs for a guide by searching Yandex Maps.

    Returns dict: {basename: url, ...}
    """
    try:
        places = _load_places(guide)
    except Exception as e:
        print("Error loading guide {}: {}".format(guide, e), file=sys.stderr)
        return {}

    result: dict[str, str] = {}
    city = "Москва"

    for i, place in enumerate(places, 1):
        name = place.get("name", "?")
        images = place.get("images") or []
        basenames = [_basename(img) for img in images]

        if not basenames:
            continue

        # Avoid printing non-ASCII place names to keep Windows consoles happy.
        print(
            "[{}/{}] Searching item {} in guide {}".format(
                i, len(places), i, guide,
            ),
        )

        if dry_run:
            print("  DRY RUN: Would search Yandex Maps for item {} in guide {}".format(i, guide))
            # Assign placeholder URLs
            for bn in basenames:
                result[bn] = "https://example.com/placeholder.jpg"
            continue

        # Search Yandex Maps
        yandex_urls = get_place_images(name, city=city, max_images=len(basenames))

        if not yandex_urls:
            print(
                "  Warning: No images found for {}. Using placeholders.".format(name),
                file=sys.stderr,
            )
            # Use placeholder or skip
            for bn in basenames:
                result[bn] = "https://example.com/placeholder.jpg"
            continue

        # Assign URLs to basenames
        for idx, bn in enumerate(basenames):
            if idx < len(yandex_urls):
                result[bn] = yandex_urls[idx]
            else:
                # Reuse last URL if we have fewer Yandex images than basenames
                result[bn] = yandex_urls[-1] if yandex_urls else "https://example.com/placeholder.jpg"

        print("  Found {} image URL(s) (saved to data; run build_pdf to download)".format(len(yandex_urls)))

    return result


def format_python_dict(
    d: dict[str, str],
    var_name: str,
    fallbacks_var_name: str | None = None,
) -> str:
    """Format dict as Python code for *_image_urls.py file."""
    if fallbacks_var_name is None:
        fallbacks_var_name = var_name.replace("_DOWNLOADS", "_FALLBACKS")
    lines = [
        "# -*- coding: utf-8 -*-",
        '"""Image URLs from Yandex Maps (auto-generated).',
        "",
        "Generated by scripts/generate_yandex_image_urls.py",
        "Source: Yandex Maps search by place name.",
        '"""',
        "{}: dict[str, str] = {{".format(var_name),
    ]

    for key, value in sorted(d.items()):
        # Escape quotes in value
        safe_value = value.replace('"', '\\"')
        lines.append('    "{}": "{}",'.format(key, safe_value))

    lines.append("}")
    lines.append("")
    lines.append("{}: dict[str, list[str]] = {{}}".format(fallbacks_var_name))
    return "\n".join(lines)


def main() -> int:
    """Generate image URLs for all guides or a specific guide."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate image URLs from Yandex Maps",
    )
    parser.add_argument(
        "--guide",
        choices=GUIDES,
        help="Generate for specific guide only",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Dry run (don't search, use placeholders)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=_PROJECT_ROOT / "data",
        help="Output directory for generated files",
    )

    args = parser.parse_args()

    guides_to_process = [args.guide] if args.guide else GUIDES

    # Map guide name to variable name and filename
    guide_to_var = {
        "monasteries": ("IMAGE_DOWNLOADS", "image_urls.py"),
        "places_of_worship": ("PLACES_OF_WORSHIP_IMAGE_DOWNLOADS", "places_of_worship_image_urls.py"),
        "parks": ("PARK_IMAGE_DOWNLOADS", "park_image_urls.py"),
        "museums": ("MUSEUM_IMAGE_DOWNLOADS", "museum_image_urls.py"),
        "palaces": ("PALACE_IMAGE_DOWNLOADS", "palace_image_urls.py"),
        "buildings": ("BUILDING_IMAGE_DOWNLOADS", "building_image_urls.py"),
        "sculptures": ("SCULPTURE_IMAGE_DOWNLOADS", "sculpture_image_urls.py"),
        "places": ("PLACE_IMAGE_DOWNLOADS", "place_image_urls.py"),
        "metro": ("METRO_IMAGE_DOWNLOADS", "metro_image_urls.py"),
        "theaters": ("THEATER_IMAGE_DOWNLOADS", "theater_image_urls.py"),
        "viewpoints": ("VIEWPOINT_IMAGE_DOWNLOADS", "viewpoint_image_urls.py"),
        "cemeteries": ("CEMETERY_IMAGE_DOWNLOADS", "cemetery_image_urls.py"),
    }

    for guide in guides_to_process:
        print("\n" + "=" * 60)
        print("Processing guide: {}".format(guide))
        print("=" * 60)

        urls = generate_urls_for_guide(guide, dry_run=args.dry_run)

        if not urls:
            print("No URLs generated for {}".format(guide))
            continue

        var_name, filename = guide_to_var[guide]
        output_path = args.output_dir / filename

        code = format_python_dict(urls, var_name)

        if args.dry_run:
            print("\nWould write to {}:".format(output_path))
            print(code[:500] + "..." if len(code) > 500 else code)
        else:
            output_path.write_text(code, encoding="utf-8")
            print("\nWrote {} URLs to {}".format(len(urls), output_path))
            print(
                "  Images are NOT downloaded here. Run:\n"
                "    python scripts/build_pdf.py --guide {} --download-only\n"
                "  to download images into output/images/<guide_subdir>/.".format(guide),
            )

    return 0


if __name__ == "__main__":
    sys.exit(main())
