# -*- coding: utf-8 -*-
"""Wave 1 worship place supplements (20 per DE / EN / AM guides)."""

from __future__ import annotations

# style_key, suffix, name_ru, name_en, year, city_ru, city_en,
# history_ru, history_en, commons_url, city_ref (city:slug)
WorshipSeed = tuple[str, str, str, str, str, str, str, str, str, str, str]

AMERICAN_ECCLESIASTICAL_MIGRATION: list[tuple[str, str, str]] = [
    ("st_patricks_cathedral", "gothic_revival", "st_patricks_nyc"),
    ("st_patricks_old_cathedral", "gothic_revival", "st_patricks_old_nyc"),
    ("trinity_church", "gothic_revival", "trinity_nyc"),
    ("st_ignatius_loyola", "victorian_americas", "st_ignatius_loyola"),
    ("st_cecilia", "gothic_revival", "st_cecilia_nyc"),
    ("notre_dame_basilica", "latin_colonial_baroque", "notre_dame_montreal"),
    ("saint_joseph_oratory", "midcentury_modern", "saint_joseph_oratory"),
    ("mary_queen_of_the_world", "beaux_arts", "mary_queen_of_the_world"),
    ("basilica_st_joseph", "midcentury_modern", "basilica_st_joseph_montreal"),
    ("basilica_st_patrick", "gothic_revival", "st_patricks_montreal"),
]

# old_suffix -> (name_ru, name_en, year, city_ru, city_en, desc_ru, desc_en,
# history_ru, history_en, commons_url)
AmericanEcclesiasticalSource = tuple[str, str, str, str, str, str, str, str, str, str]

AMERICAN_ECCLESIASTICAL_SOURCES: dict[str, AmericanEcclesiasticalSource] = {
    "st_patricks_cathedral": (
        "Собор Святого Патрика", "St. Patrick's Cathedral", "1858–1879",
        "Нью-Йорк", "New York",
        "Неоготический кафедральный собор на Пятой авеню.",
        "Neo-Gothic cathedral on Fifth Avenue.",
        "Построен в эпоху роста католического населения города.",
        "Built as immigrant Catholicism shaped the metropolis.",
        "https://upload.wikimedia.org/wikipedia/commons/8/86/Spires_of_St_Patricks_Cathedral_Rising_Above_Fifth_Avenue_2019-09-30_18-19.jpg",
    ),
    "st_patricks_old_cathedral": (
        "Базилика Старого Собора Святого Патрика",
        "Basilica of St. Patrick's Old Cathedral", "1809–1815",
        "Нью-Йорк", "New York",
        "Первый кафедральный собор Нью-Йорка в Ноу-Литл-Италия.",
        "First cathedral of New York in NoLita.",
        "Построен до переноса кафедры на Пятую авеню.",
        "Built before the see moved to Fifth Avenue.",
        "https://upload.wikimedia.org/wikipedia/commons/5/5d/St._Patrick%27s_%28Old%29_Cathedral%2C_Mott_Street%2C_New_York_City.jpg",
    ),
    "trinity_church": (
        "Троицкая церковь", "Trinity Church", "1846",
        "Нью-Йорк", "New York",
        "Англиканская церковь на Уолл-стрит с готическим шпилем.",
        "Anglican church on Wall Street with Gothic spire.",
        "Третья постройка прихода с 1696 года.",
        "Third church of the parish founded in 1696.",
        "https://upload.wikimedia.org/wikipedia/commons/2/2d/Trinity_Church_NYC_004b.JPG",
    ),
    "st_ignatius_loyola": (
        "Базилика Святого Игнатия Лойолы",
        "Basilica of St. Ignatius Loyola", "1898",
        "Нью-Йорк", "New York",
        "Иезуитская париковая церковь на Парк-авеню.",
        "Jesuit parish church on Park Avenue.",
        "Неоренессансный храм прихода иезуитов.",
        "Neo-Renaissance Jesuit parish church.",
        "https://upload.wikimedia.org/wikipedia/commons/3/38/Church_of_St._Ignatius_Loyola_%28New_York_City%29.jpg",
    ),
    "st_cecilia": (
        "Базилика Святой Сесилии", "Basilica of Saint Cecilia", "1883–1886",
        "Нью-Йорк", "New York",
        "Римско-католический приход Святой Цецилии в Ист-Гарлеме.",
        "Roman Catholic parish of St. Cecilia in East Harlem.",
        "Немецко-ирландский приход с кирпичным неоготическим храмом.",
        "German-Irish parish with a brick Neo-Gothic church.",
        "https://upload.wikimedia.org/wikipedia/commons/0/03/%28King1893NYC%29_pg405_ST._CECILIAS_CHURCH%2C_ROMAN_CATHOLIC%2C_EAST_106TH_STREET.jpg",
    ),
    "notre_dame_basilica": (
        "Базилика Нотр-Дам", "Notre-Dame Basilica", "1824–1829",
        "Монреаль", "Montreal",
        "Французское барокко Старого Монреаля с позолоченным интерьером.",
        "French Baroque basilica of Old Montreal with gilded interior.",
        "Заменила колониальную приходскую церковь.",
        "Replaced a colonial parish church.",
        "https://upload.wikimedia.org/wikipedia/commons/d/d0/Exterior_of_Notre-Dame_de_Montr%C3%A9al_Basilica.jpg",
    ),
    "saint_joseph_oratory": (
        "Ораторий Святого Иосифа",
        "Saint Joseph's Oratory of Mount Royal", "1924–1967",
        "Монреаль", "Montreal",
        "Крупнейшая церковь Канады на склоне Мон-Рояля.",
        "Canada's largest church on Mount Royal.",
        "Возведён братом Андре; национальное святилище.",
        "Built by Brother André; national shrine.",
        "https://upload.wikimedia.org/wikipedia/commons/6/69/Oratoire_Saint-Joseph_du_Mont-Royal_-_Montreal.jpg",
    ),
    "mary_queen_of_the_world": (
        "Собор Марии, Королевы Мира",
        "Mary, Queen of the World Cathedral", "1875–1894",
        "Монреаль", "Montreal",
        "Кафедральный собор в масштабе собора Святого Петра в Риме.",
        "Cathedral scaled to St. Peter's in Rome.",
        "Построен как заявление католического присутствия.",
        "Built to assert Catholic presence in a fast-growing metropolis.",
        "https://upload.wikimedia.org/wikipedia/commons/3/31/Catedral_de_Mar%C3%ADa_Reina_del_Mundo%2C_Montreal%2C_Canad%C3%A1%2C_2017-08-11%2C_DD_37-39_HDR.jpg",
    ),
    "basilica_st_joseph": (
        "Базилика Святого Иосифа", "Basilica of St. Joseph", "1924–1967",
        "Монреаль", "Montreal",
        "Интерьер малой базилики на Мон-Рояле.",
        "Interior of the Mount Royal minor basilica.",
        "Главный молитвенный зал оратория.",
        "Main worship hall of the oratory.",
        "https://upload.wikimedia.org/wikipedia/commons/7/70/Basilica_in_St._Joseph_Oratory.jpg",
    ),
    "basilica_st_patrick": (
        "Базилика Святого Патрика", "Basilica of St. Patrick", "1876–1894",
        "Монреаль", "Montreal",
        "Готическое возрождение ирландского прихода у Старого порта.",
        "Gothic Revival basilica of Montreal's Irish community.",
        "Спроектирована Жозефом-Октавом Коте.",
        "Designed by Joseph-Octave Côté.",
        "https://upload.wikimedia.org/wikipedia/commons/1/1e/Saint_Patrick_Basilica_Montreal.jpg",
    ),
}

WAVE1_WORSHIP: dict[str, list[WorshipSeed]] = {
    "german_architecture": [
        (
            "romanesque", "speyer_cathedral", "Кафедральный собор Шпайера",
            "Speyer Cathedral", "1030–1106", "Шпайер", "Speyer",
            "Имперский собор с подземной усыпальницей Салических императоров.",
            "Imperial cathedral with crypt burials of Salian emperors.",
            "https://upload.wikimedia.org/wikipedia/commons/4/4f/Speyer_Cathedral_in_Speyer.jpg",
            "",
        ),
        (
            "romanesque", "aachen_cathedral", "Аахенский собор",
            "Aachen Cathedral", "796–803", "Аахен", "Aachen",
            "Капелла Карла Великого — жемчужина каролингского зодчества.",
            "Palatine chapel of Charlemagne — Carolingian masterpiece.",
            "https://upload.wikimedia.org/wikipedia/commons/4/48/Aachener_Dom_2014.jpg",
            "",
        ),
        (
            "romanesque", "worms_cathedral", "Собор Вормса",
            "Worms Cathedral", "XI–XIII вв.", "Вормс", "Worms",
            "Один из трёх имперских кафедральных соборов Рейна.",
            "One of three Rhenish imperial cathedrals.",
            "",
            "",
        ),
        (
            "romanesque", "bamberg_cathedral", "Бамбергский собор",
            "Bamberg Cathedral", "1004–1237", "Бамберг", "Bamberg",
            "Четыре башни на холме; могила императора Генриха II.",
            "Four towers on a hill; tomb of Emperor Henry II.",
            "",
            "",
        ),
        (
            "gothic", "cologne_cathedral", "Кёльнский собор",
            "Cologne Cathedral", "1248–1880", "Кёльн", "Cologne",
            "Двухбашенный готический собор с реликвией волхвов.",
            "Twin-spired Gothic cathedral with Shrine of the Three Kings.",
            "https://upload.wikimedia.org/wikipedia/commons/1/1b/K%C3%B6lner_Dom_mit_Rhein.jpg",
            "",
        ),
        (
            "gothic", "ulm_minster", "Собор Ульма",
            "Ulm Minster", "1377–1890", "Ульм", "Ulm",
            "Самый высокий церковный шпиль мира.",
            "World's tallest church spire.",
            "",
            "",
        ),
        (
            "gothic", "munich_frauenkirche", "Фрауэнкирхе",
            "Frauenkirche Munich", "XV в.", "Мюнхен", "Munich",
            "Купола-луковицы — символ Мюнхена.",
            "Onion domes — symbol of Munich.",
            "",
            "",
        ),
        (
            "gothic", "vienna_stephansdom", "Собор Святого Стефана",
            "St. Stephen's Cathedral Vienna", "XII–XV вв.", "Вена", "Vienna",
            "Мозаичная крыша и южная башня Вены.",
            "Tiled roof and south tower of Vienna.",
            "",
            "",
        ),
        (
            "rococo", "wieskirche", "Визкирхе",
            "Wieskirche", "1745–1754", "Штаинген", "Steingaden",
            "Паломническая церковь в Альпах.",
            "Alpine pilgrimage church.",
            "",
            "",
        ),
        (
            "baroque", "dresden_frauenkirche", "Фрауэнкирхе Дрездена",
            "Dresden Frauenkirche", "1726–1743", "Дрезден", "Dresden",
            "Восстановленный купол барокко после 1945 года.",
            "Baroque dome rebuilt after 1945.",
            "",
            "",
        ),
        (
            "historicism", "berlin_cathedral", "Берлинский собор",
            "Berlin Cathedral", "1894–1905", "Берлин", "Berlin",
            "Неоренессансный купол на Музейном острове.",
            "Neo-Renaissance dome on Museum Island.",
            "https://upload.wikimedia.org/wikipedia/commons/4/47/Berliner_Dom%2C_Ostseite%2C_160402%2C_ako.jpg",
            "berlin:berlin_cathedral",
        ),
        (
            "historicism", "new_synagogue_berlin", "Новая синагога",
            "New Synagogue Berlin", "1866", "Берлин", "Berlin",
            "Мавританско-романский фасад еврейской общины.",
            "Moorish Revival façade of Berlin's Jewish community.",
            "",
            "",
        ),
        (
            "historicism", "vienna_votivkirche", "Вотивкирхе",
            "Votivkirche", "1856–1879", "Вена", "Vienna",
            "Неоготика благодарственного храма.",
            "Neo-Gothic church of thanksgiving.",
            "",
            "",
        ),
        (
            "expressionism", "kaiser_wilhelm_memorial", "Мемориальная церковь",
            "Kaiser Wilhelm Memorial Church", "1895", "Берлин", "Berlin",
            "Руины башни и современный зал Эгона Эйермана.",
            "Ruined tower and Egon Eiermann's modern hall.",
            "https://upload.wikimedia.org/wikipedia/commons/e/e9/Tower_of_Kaiser_Wilhelm_Memorial_Church_2014-07-12.jpg",
            "berlin:berlin_kaiser_wilhelm_memorial_church",
        ),
        (
            "postwar_modern", "dresden_synagogue", "Синагога Дрездена",
            "New Dresden Synagogue", "2001", "Дрезден", "Dresden",
            "Современная синагога на месте разрушенной 1938 года.",
            "Modern synagogue on the site destroyed in 1938.",
            "",
            "",
        ),
        (
            "contemporary", "cologne_mosque", "Центральная мечеть Кёльна",
            "Cologne Central Mosque", "2017", "Кёльн", "Cologne",
            "Крупнейшая мечеть Германии с турецкими минаретами.",
            "Germany's largest mosque with Turkish minarets.",
            "",
            "",
        ),
        (
            "contemporary", "berlin_moschee", "Мечеть Сехитлик",
            "Şehitlik Mosque Berlin", "1999–2005", "Берлин", "Berlin",
            "Османский стиль мечети для турецкой общины.",
            "Ottoman-style mosque for Berlin's Turkish community.",
            "",
            "berlin:berlin_moschee_wilmersdorf",
        ),
        (
            "contemporary", "rykestrasse_synagogue", "Синагога Рыбная улица",
            "Rykestrasse Synagogue", "1904", "Берлин", "Berlin",
            "Крупнейшая синагога Германии, восстановленная.",
            "Germany's largest synagogue, restored.",
            "",
            "",
        ),
        (
            "gothic", "regensburg_cathedral", "Собор Регенсбурга",
            "Regensburg Cathedral", "XIII–XVI вв.", "Регенсбург", "Regensburg",
            "Готический собор на Дунае.",
            "Gothic cathedral on the Danube.",
            "",
            "",
        ),
        (
            "romanesque", "mainz_cathedral", "Собор Майнца",
            "Mainz Cathedral", "XI–XIII вв.", "Майнц", "Mainz",
            "Красный песчаник на берегу Рейна.",
            "Red sandstone on the Rhine.",
            "",
            "",
        ),
    ],
    "english_architecture": [
        (
            "norman", "durham_cathedral", "Собор Дарема",
            "Durham Cathedral", "1093–1133", "Дарем", "Durham",
            "Романский собор с ребристыми сводами.",
            "Romanesque cathedral with rib vaults.",
            "",
            "",
        ),
        (
            "norman", "ely_cathedral", "Собор Или",
            "Ely Cathedral", "1083–1375", "Или", "Ely",
            "Октогон и западная башня.",
            "Octagon and west tower.",
            "",
            "",
        ),
        (
            "norman", "southwark_cathedral", "Собор Саутарка",
            "Southwark Cathedral", "XIII в.", "Лондон", "London",
            "Приходский собор у Borough Market.",
            "Parish cathedral by Borough Market.",
            "",
            "",
        ),
        (
            "english_gothic", "york_minster", "Йоркский минстер",
            "York Minster", "1220–1472", "Йорк", "York",
            "Великое восточное окно.",
            "Great East Window.",
            "",
            "",
        ),
        (
            "english_gothic", "salisbury_cathedral", "Солсберийский собор",
            "Salisbury Cathedral", "1220–1258", "Солсбери", "Salisbury",
            "Самый высокий шпиль Британии.",
            "Britain's tallest spire.",
            "",
            "",
        ),
        (
            "english_gothic", "canterbury_cathedral", "Кентерберийский собор",
            "Canterbury Cathedral", "1070–", "Кентербери", "Canterbury",
            "Место паломничества и убийства Бекета.",
            "Pilgrimage site and Becket martyrdom.",
            "",
            "",
        ),
        (
            "english_gothic", "lincoln_cathedral", "Линкольнский собор",
            "Lincoln Cathedral", "1072–1311", "Линкольн", "Lincoln",
            "Тройной западный фасад и шпиль.",
            "Triple west front and spire.",
            "",
            "",
        ),
        (
            "georgian", "bath_abbey", "Аббатство Бат",
            "Bath Abbey", "1499–1616", "Бат", "Bath",
            "Фанерные своды на фоне римских бань.",
            "Fan vaults beside Roman Baths.",
            "",
            "",
        ),
        (
            "georgian", "bevis_marks_synagogue", "Синагога Бевис Маркс",
            "Bevis Marks Synagogue", "1701", "Лондон", "London",
            "Старейшая синагога Великобритании в непрерывном использовании.",
            "Britain's oldest synagogue in continuous use.",
            "",
            "",
        ),
        (
            "victorian", "liverpool_cathedral", "Собор Ливерпуля",
            "Liverpool Cathedral", "1904–1978", "Ливерпуль", "Liverpool",
            "Крупнейший англиканский собор в мире.",
            "Largest Anglican cathedral in the world.",
            "",
            "",
        ),
        (
            "victorian", "westminster_cathedral", "Вестминстерский кафедральный собор",
            "Westminster Cathedral", "1895–1903", "Лондон", "London",
            "Католический собор в неовизантийском стиле.",
            "Catholic cathedral in Neo-Byzantine style.",
            "",
            "",
        ),
        (
            "modernism", "coventry_cathedral", "Собор Ковентри",
            "Coventry Cathedral", "1956–1962", "Ковентри", "Coventry",
            "Базилика Спенса рядом с руинами войны.",
            "Spence's basilica beside war ruins.",
            "",
            "",
        ),
        (
            "contemporary", "london_central_mosque", "Лондонская центральная мечеть",
            "London Central Mosque", "1977", "Лондон", "London",
            "Золотой купол у Риджентс-парка.",
            "Golden dome near Regent's Park.",
            "",
            "",
        ),
        (
            "palladian_wren", "st_martin_in_fields", "Церковь Мартина-в-полях",
            "St Martin-in-the-Fields", "1726", "Лондон", "London",
            "Портик на Трафальгарской площади.",
            "Portico on Trafalgar Square.",
            "",
            "",
        ),
        (
            "georgian", "boston_old_north", "Старая Северная церковь",
            "Old North Church", "1723", "Бостон", "Boston",
            "Сигнальные фонари Пола Ревира.",
            "Paul Revere's signal lanterns.",
            "https://upload.wikimedia.org/wikipedia/commons/5/51/Old_North_Church_%286001949500%29.jpg",
            "boston:boston_old_north_church",
        ),
        (
            "georgian", "boston_kings_chapel", "Капелла короля",
            "King's Chapel", "1754", "Бостон", "Boston",
            "Первый англиканский приход Бостона.",
            "Boston's first Anglican parish.",
            "https://upload.wikimedia.org/wikipedia/commons/3/35/Boston_Kings_Chapel_NW_Portikus_9448_20190429.jpg",
            "boston:boston_kings_chapel",
        ),
        (
            "georgian", "philadelphia_christ_church", "Церковь Христа",
            "Christ Church Philadelphia", "1744", "Филадельфия", "Philadelphia",
            "Колониальная англиканская церковь Старого города.",
            "Colonial Anglican church of Old City.",
            "https://upload.wikimedia.org/wikipedia/commons/3/3b/Christ_Church_from_2nd_Street.jpg",
            "philadelphia:philadelphia_christ_church_philadelphia",
        ),
        (
            "brutalism", "clifton_cathedral", "Собор Клифтона",
            "Clifton Cathedral", "1969–1973", "Бристоль", "Bristol",
            "Бетонный католический собор.",
            "Concrete Catholic cathedral.",
            "",
            "",
        ),
        (
            "art_deco", "willesden_synagogue", "Синагога Виллсден",
            "Willesden United Synagogue", "1937", "Лондон", "London",
            "Ар-деко синагога северо-западного Лондона.",
            "Art Deco synagogue in northwest London.",
            "",
            "",
        ),
        (
            "tudor", "st_james_piccadilly", "Церковь Святого Иакова",
            "St James's Church Piccadilly", "1684", "Лондон", "London",
            "Церковь Вренa на Пикадилли.",
            "Wren church on Piccadilly.",
            "",
            "",
        ),
    ],
    "american_architecture": [
        (
            "federal", "philadelphia_christ_church", "Церковь Христа",
            "Christ Church Philadelphia", "1744", "Филадельфия", "Philadelphia",
            "Колониальная англиканская церковь Старого города.",
            "Colonial Anglican church of Old City.",
            "https://upload.wikimedia.org/wikipedia/commons/3/3b/Christ_Church_from_2nd_Street.jpg",
            "philadelphia:philadelphia_christ_church_philadelphia",
        ),
        (
            "federal", "boston_old_north", "Старая Северная церковь",
            "Old North Church", "1723", "Бостон", "Boston",
            "Фонари сигнала Пола Ревира.",
            "Paul Revere signal lanterns.",
            "https://upload.wikimedia.org/wikipedia/commons/5/51/Old_North_Church_%286001949500%29.jpg",
            "boston:boston_old_north_church",
        ),
        (
            "greek_revival", "boston_kings_chapel", "Капелла короля",
            "King's Chapel", "1754", "Бостон", "Boston",
            "Каменная англиканская капелла.",
            "Stone Anglican chapel.",
            "https://upload.wikimedia.org/wikipedia/commons/3/35/Boston_Kings_Chapel_NW_Portikus_9448_20190429.jpg",
            "boston:boston_kings_chapel",
        ),
        (
            "victorian_americas", "riverside_church", "Риверсайд-черч",
            "Riverside Church", "1930", "Нью-Йорк", "New York",
            "Неоготическая башня Морнингсайд-Хайтс.",
            "Neo-Gothic tower in Morningside Heights.",
            "",
            "",
        ),
        (
            "beaux_arts", "brooklyn_cathedral", "Кафедральный собор Бруклина",
            "Cathedral Basilica of Our Lady of Perpetual Help", "1873–1920",
            "Бруклин", "Brooklyn",
            "Купол над Проспект-хайтс.",
            "Dome above Prospect Heights.",
            "",
            "",
        ),
        (
            "art_deco_americas", "chicago_temple", "Синагога Темпл",
            "Chicago Temple Building", "1924", "Чикаго", "Chicago",
            "Небоскрёб с методистской церковью наверху.",
            "Skyscraper with Methodist church at top.",
            "",
            "",
        ),
        (
            "international_style", "us_air_force_chapel", "Капелла ВВС США",
            "Cadet Chapel Colorado Springs", "1962", "Колорадо-Спрингс",
            "Colorado Springs",
            "Семнадцать шпилей из алюминия.",
            "Seventeen aluminium spires.",
            "",
            "",
        ),
        (
            "midcentury_modern", "los_angeles_cathedral", "Собор Нашей Ледицы Ангелов",
            "Cathedral of Our Lady of the Angels", "2002", "Лос-Анджелес",
            "Los Angeles",
            "Бетон и алебастр Мурая.",
            "Murray's concrete and alabaster.",
            "https://upload.wikimedia.org/wikipedia/commons/1/18/Exterior_of_Cathedral_of_Our_Lady_of_the_Angels_dllu.jpg",
            "los_angeles:los_angeles_cathedral",
        ),
        (
            "gothic_revival", "washington_national_cathedral", "Национальный собор Вашингтона",
            "Washington National Cathedral", "1907–1990", "Вашингтон",
            "Washington D.C.",
            "Англиканский кафедральный собор на Маунт-Сейнт-Олбан.",
            "Anglican cathedral on Mount St. Alban.",
            "",
            "",
        ),
        (
            "postmodern", "crystal_cathedral", "Хрустальный собор",
            "Christ Cathedral", "1980", "Гарден-Гроув", "Garden Grove",
            "Стеклянный фасад Филиппа Джонсона.",
            "Philip Johnson's glass façade.",
            "",
            "",
        ),
        (
            "contemporary_americas", "dearborn_mosque", "Исламский центр Америки",
            "Islamic Center of America", "2005", "Дирборн", "Dearborn",
            "Крупнейшая мечеть Северной Америки.",
            "Largest mosque in North America.",
            "",
            "",
        ),
        (
            "colonial_americas", "san_xavier", "Миссия Сан-Ксавье",
            "Mission San Xavier del Bac", "1783–1797", "Тусон", "Tucson",
            "Испанская миссия в пустыне Аризоны.",
            "Spanish mission in the Arizona desert.",
            "",
            "",
        ),
        (
            "gothic_revival", "montreal_christ_church", "Англиканская церковь Крайст-Чёрч",
            "Christ Church Cathedral Montreal", "1857–1859", "Монреаль", "Montreal",
            "Собор в торговом комплексе.",
            "Cathedral embedded in a shopping complex.",
            "",
            "",
        ),
        (
            "contemporary_americas", "central_synagogue", "Центральная синагога",
            "Central Synagogue New York", "1872", "Нью-Йорк", "New York",
            "Мавританское возрождение на Лексингтон-авеню.",
            "Moorish Revival on Lexington Avenue.",
            "",
            "",
        ),
        (
            "latin_modernism", "rio_cathedral", "Кафедральный собор Рио",
            "Rio de Janeiro Cathedral", "1964–1979", "Рио-де-Жанейро",
            "Rio de Janeiro",
            "Конический бетонный собор Нерей Кантуни.",
            "Niemeyer's conical concrete cathedral.",
            "",
            "",
        ),
        (
            "gothic_revival", "st_thomas_fifth_avenue", "Церковь Святого Фомы",
            "St. Thomas Church Fifth Avenue", "1914", "Нью-Йорк", "New York",
            "Неоготика на Пятой авеню.",
            "Neo-Gothic on Fifth Avenue.",
            "",
            "",
        ),
        (
            "latin_colonial_baroque", "buenos_aires_metropolitan", "Метрополитен-собор Буэнос-Айреса",
            "Buenos Aires Metropolitan Cathedral", "1758–1799", "Буэнос-Айрес",
            "Buenos Aires",
            "Колониальный фасад на Пласа-де-Майо.",
            "Colonial façade on Plaza de Mayo.",
            "",
            "",
        ),
        (
            "federal", "philadelphia_cathedral_basilica", "Кафедральный собор Св. Петра и Павла",
            "Cathedral Basilica of SS. Peter and Paul", "1846–1864",
            "Филадельфия", "Philadelphia",
            "Неоренессансный купол на Логан-сквер.",
            "Neo-Renaissance dome on Logan Square.",
            "",
            "",
        ),
        (
            "international_style", "unitarian_church_dallas", "Первый унитарианский собор",
            "First Unitarian Church Dallas", "1962", "Даллас", "Dallas",
            "Бетонный храм Фрэнка Ллойда Райта.",
            "Frank Lloyd Wright concrete church.",
            "",
            "",
        ),
        (
            "prairie_style", "unity_temple", "Храм Юнити",
            "Unity Temple", "1905–1908", "Оук-Парк", "Oak Park",
            "Бетонный храм Фрэнка Ллойда Райта.",
            "Frank Lloyd Wright's concrete Unity Temple.",
            "",
            "",
        ),
    ],
}


def wave1_seeds(module: str) -> list[WorshipSeed]:
    rows = WAVE1_WORSHIP.get(module, [])
    if len(rows) != 20:
        raise ValueError(
            "{} wave1 worship count is {}, expected 20".format(
                module,
                len(rows),
            ),
        )
    return rows
